apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: example-container
        image: busybox
        command: ["echo", "Checking the CICD setups"]
      restartPolicy: Never
  backoffLimit: 4
