---
- name: Create EKS Cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create the EKS cluster
      command: eksctl create cluster --name my-cluster --region us-west-2 --nodegroup-name my-nodes --node-type t3.medium --nodes 3 --nodes-min 1 --nodes-max 4
      register: eks_cluster_creation

    - name: Output the cluster details
      debug:
        var: eks_cluster_creation
