---
- name: Create EKS Cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create the EKS cluster
      command: eksctl create cluster --name test-cluster --region ap-south-1 --nodegroup-name workers --node-type t2.micro --nodes 2 --nodes-min 1 --nodes-max 3
      register: eks_cluster_creation

    - name: Ensure cluster creation succeeded
      fail:
        msg: "Cluster creation failed. See details above."
      when: eks_cluster_creation.rc != 0

    - name: Output the cluster details
      debug:
        var: eks_cluster_creation
